application: triple-upgrade-622
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /js/vendor
  static_dir: js/vendor
- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
